-- 102_procedure_performer.sql — PROC_PERFORMER_V1: «процедура приходит тому,
-- кого выбрали», и приходит она в том числе МЕДСЕСТРЕ.
--
-- Владелец, дословно: «procedures, either can be for doctors or nurses, or
-- either can be for the procedure room ambulator patients or can be for
-- stationary patients. and they too should come to the employee. as a selected
-- service provider when setting a service and the registator selects the
-- provider.»
--
-- ─── ПОЧЕМУ ОТДЕЛЬНАЯ КОЛОНКА, А НЕ doctor_id ──────────────────────────────
--
-- В системе ДВЕ строки услуги, и слово doctor_id значит в них РАЗНОЕ.
--
--   visit_services.doctor_id   = ИСПОЛНИТЕЛЬ. Так уже есть: кнопка «Взять» в
--       очереди процедур (views/procedures.js, PROC_UNASSIGNED_V1) пишет туда
--       id того, кто нажал, — и это регулярно медсестра. Деньги идут за
--       исполнителем (reports.js doctor_salaries группирует по vs.doctor_id),
--       и это ПРАВИЛЬНО: процент получает тот, кто сделал. Новая колонка здесь
--       раздвоила бы одно понятие на два и разошлась бы с кабинетом врача,
--       дашбордом и зарплатным отчётом. Её здесь НЕТ намеренно.
--
--   admission_services.doctor_id = ЛЕЧАЩИЙ ВРАЧ, и это ДЕНЕЖНАЯ колонка.
--       views/ward-beds.js пишет туда attending_doctor_id со словами «выработка
--       за услугу должна доставаться ему», а rpc/billing.js
--       (createInvoiceForAdmission) ЦЕНИТ по ней строку счёта:
--           unitPriceFor({ doctorId: row.doctor_id, … })
--       — личная цена врача из users.service_rates побеждает цену каталога.
--       Записать туда медсестру значит ДВА раза тронуть деньги: отобрать
--       выработку у лечащего и молча уронить цену в счёте пациента с личной
--       цены врача до каталожной. Поэтому исполнитель палатной процедуры
--       живёт в СВОЕЙ колонке, а doctor_id остаётся нетронутым.
--
-- Проверено тестом (102.test.js и rpc/procedures.test.js): счёт госпитализации
-- после назначения медсестры выставляется на ту же сумму.
--
-- ─── БЕЗОПАСНОСТЬ НА ЖИВОЙ БАЗЕ ────────────────────────────────────────────
--
-- ADD COLUMN строк не трогает, поэтому журнал филиалов (084_sync_journal.sql)
-- не шевелится. У admission_services его и нет: таблицы стационара не ездят
-- между зданиями вовсе (у них нет ни uid, ни sync_origin — см. шапку 091),
-- и это же есть ответ на правило «палата — своего здания»: чужой палатной
-- строки в этой базе не бывает по устройству, а не по фильтру.
--
-- У существующих строк колонка = NULL, то есть «исполнитель не назначен» —
-- ровно то, чем они и были до сегодняшнего дня.

ALTER TABLE admission_services ADD COLUMN performer_id INTEGER REFERENCES users(id);

-- Очередь процедур спрашивает «что назначено ЭТОМУ человеку» на каждой
-- отрисовке экрана. Без индекса это скан всей таблицы начислений стационара —
-- самой длинной в базе лежачей клиники.
CREATE INDEX idx_admission_services_performer ON admission_services(performer_id);
