-- 139_invoice_voided_at.sql — CANCEL_MEANS_CANCEL_V1: КОГДА СЧЁТ ОТМЕНЁН.
--
-- Владелец (2026-09-18): «why in the cashier's cancelled invoices goes to the
-- unpaid? and if we were to cancel it should be cancelled».
--
-- Плитка «ОТМЕНЁН» в «Приёме оплат» считала отменённые счета по дню, когда
-- счёт был ВЫСТАВЛЕН (created_at): у счёта не было своей даты отмены. Пациента
-- записали вчера, счёт отменили сегодня — и он исчезал с экрана целиком:
-- плитка показывала 0, будто отмены не было.
--
-- voided_at — момент отмены (void) или возврата (refunded). Плитка и список
-- считают отменённые по нему. У старых отменённых счетов колонка пуста, и для
-- них остаётся прежнее правило по created_at — ничего задним числом не
-- переписывается.
--
-- ТОЛЬКО ADD COLUMN.
ALTER TABLE invoices ADD COLUMN voided_at TEXT;
