-- CONTROL_PLANE_V1 — the vendor's registry of clinics.
--
-- This database answers "who is running Easy-Med, on what, paying for what". It
-- holds NO patient data of any kind and must never grow a column that could: the
-- clinic side is built to be physically incapable of sending any, and this schema
-- is the second line of that guarantee.

CREATE TABLE clinics (
  -- The identity everything hangs off. Generated by us, never reused, and baked
  -- into every signed licence — a licence for one clinic is rejected by another
  -- with `wrong_clinic`, which is what makes two clinics unconfusable.
  --
  -- Deliberately case-sensitive (SQLite's default TEXT comparison). clinic_id is
  -- generated by us and never the thing a human types down a phone line (that is
  -- enrollment_code and the unlock challenge) — so there is no typo to forgive,
  -- and folding case would let e.g. 'c-000047' and 'C-000047' collide in ways a
  -- signed licence never intended. See migrations/001.test.js for the pinned
  -- case-sensitivity behaviour.
  clinic_id        TEXT PRIMARY KEY,
  name             TEXT NOT NULL,
  contact_phone    TEXT,
  contact_name     TEXT,

  -- Consumed at first run, then cleared. Short enough to read down a phone.
  enrollment_code  TEXT UNIQUE,
  -- Issued at enrollment; authenticates every later check-in.
  install_token    TEXT UNIQUE,
  -- Shared secret behind telephone unlock codes. The clinic holds a copy.
  unlock_secret    TEXT NOT NULL,

  -- 'active' | 'unpaid'. Drives the WORDING the clinic sees, and whether the
  -- licence is re-armed at all. CHECK constraint because this column is read by
  -- every check-in to decide re-arming: a typo like 'aktive' would silently mean
  -- "not active" everywhere downstream, with no error anywhere near the typo.
  subscription     TEXT NOT NULL DEFAULT 'active' CHECK (subscription IN ('active', 'unpaid')),
  -- Paid up to. NULL means no end date recorded. Once today passes it, check-in
  -- stops re-arming and the clinic's own 14-day ladder takes over.
  subscription_until TEXT,

  last_seen_at     TEXT,
  last_version     TEXT,
  last_fingerprint TEXT,

  notes            TEXT,
  created_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
  -- Retiring a clinic sets active=0; the row and its clinic_id are kept, not
  -- deleted, so the id can never be reissued to a different clinic (a licence
  -- signed for the old clinic must never come to verify against a new one).
  -- Nothing in this schema forbids a hard DELETE — migrations/001.test.js pins
  -- that deleting and re-inserting the same clinic_id is currently possible —
  -- but the application is expected to never do it for a live clinic. See
  -- control-plane/README.md.
  active           INTEGER NOT NULL DEFAULT 1
);

-- One row per module a clinic may use. A row's PRESENCE is the grant; there is
-- no `enabled` boolean, because a boolean invites "what does false mean" and the
-- answer is always "delete the row".
CREATE TABLE clinic_modules (
  clinic_id   TEXT NOT NULL REFERENCES clinics(clinic_id) ON DELETE CASCADE,
  module_key  TEXT NOT NULL,
  granted_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
  granted_by  TEXT,
  PRIMARY KEY (clinic_id, module_key)
);

-- Evidence, not state. Deliberately NOT cascaded: if a clinic row is deleted the
-- record of what it did stays, keyed by the plain id, because that is what you
-- look at when someone disputes a bill.
CREATE TABLE checkins (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  clinic_id    TEXT NOT NULL,
  at           TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
  version      TEXT,
  fingerprint  TEXT,
  payload      TEXT
);
CREATE INDEX checkins_clinic_at ON checkins (clinic_id, at DESC);

-- «Подключить модуль» leads, carried up by check-in.
CREATE TABLE module_requests (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  clinic_id    TEXT NOT NULL,
  module_key   TEXT NOT NULL,
  requested_at TEXT NOT NULL,
  received_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
  status       TEXT NOT NULL DEFAULT 'open',   -- open | granted | declined
  handled_at   TEXT,
  notes        TEXT
);
CREATE INDEX module_requests_open ON module_requests (status, received_at DESC);
